; Default build: RD130_ADM3490_Diagnose example

[platformio]
src_dir = examples/RD130_ADM3490_Diagnose
default_envs = esp32-s3-diagnose

[env:esp32-s3-diagnose]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps = symlink://${PROJECT_DIR}

[env:esp32dev-diagnose]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = symlink://${PROJECT_DIR}
